# ===========================
# DATABASE
# ===========================
spring.datasource.url=jdbc:mysql://localhost:3306/hairbook
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ===========================
# SERVER
# ===========================
server.port=8080

# ===========================
# JWT
# ===========================
jwt.secret=HaircutBookingSecretKey2024ThisIsAVeryLongSecretKeyForJWT
jwt.expiration=86400000


# ===========================
# AI (Gemini)
# ===========================
gemini.api.url=https://generativelanguage.googleapis.com
gemini.api.key=AQ.Ab8RN6KuOBP3ysKy4bw3Pt9tuH3l34K4D2mW75f5Lf44t61teQ
